### ISSUE TITLE
Screen 2 - Location and Languages selection

### ISSUE THREAD

**Issue by eefret** [eefret/AISTT#3]
Our second screen will be where we will define the project location, then, based on the configuration selected in projectType we have to scan the different strings languages and list them in the list, the after the user selects the languages he wants from the list, we can pass all this info to the main Screen and open a new project in it.

[Image Mockup](https://aistt.mybalsamiq.com/mockups/4424169.png?key=324bb0499d4605ff0cf33031e2479724dc58ede8)

This should set a global variable named projectLocation and another one named languagesMap, the first one will define the root location path, and the second path will have the language code and the file path relative to the projectLocation.

**Example**:

projectLocation = '/home/eefret/Workspace/android/myproject';
languagesMap : {
     'default': 'app/main/src/values/strings.xml',
     'en_us' : 'app/main/src/values-en/strings.xml',
     'es_es' : 'app/main/src/values-es/strings.xml
}

**Comment by chriscoderdr** [comment]
Check it.

**Comment by chriscoderdr** [comment]
<img width="859" alt="screen shot 2016-04-20 at 4 05 11 am" src="https://cloud.githubusercontent.com/assets/2073238/14667452/58ae9612-06ad-11e6-9568-3ae7ddddcad1.png">
<img width="934" alt="screen shot 2016-04-20 at 4 05 22 am" src="https://cloud.githubusercontent.com/assets/2073238/14667453/58b18a98-06ad-11e6-8ab5-31c5f3f8850d.png">
<img width="859" alt="screen shot 2016-04-20 at 4 05 31 am" src="https://cloud.githubusercontent.com/assets/2073238/14667454/58b50c5e-06ad-11e6-801f-11caba5b9303.png">
